name: 'build-test'

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: '${{ matrix.os }}: run'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_WORKSPACES }}
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        npm install
        npm run build/pack
        npm run test
